default_package: platinum
quiet_hours:
  start: "23:00"
  end: "16:00"
  enabled: true
option_expiry:
  ignore_weekend: true
  weekly_expires_friday: true
expiry_alert_thresholds:
  - 7d
  - 3d
  - 1d
price_update:
  enabled: true
  include_symbol_strike_expiry: true
  rate_limit_seconds: 2
plan_pick_window_days: 30
best_value_badge_threshold_percent: 15
realtime_progressbar: true
ksa_earnings_lookahead_days: 5
us_earnings_lookahead_days: 7
